### ISSUE TITLE
delete all from entity

### ISSUE THREAD

**Issue by mdeandreis** [arkverse/SwiftRecord#11]
I was trying to remove all data from "Test" entity. After call Test.deleteAll(), data is not removed. This line  NSManagedObjectContext.defaultContext.save() is missing 

Thanks Martin

**Comment by zaiddag** [comment]
Saving context is left up to the user, because context saving is an extremely heavy operation.
Usually, you save the context in you `applicationWillTerminate()` function so you never freeze up the UI with your context work.
To save the context in `applicationWillTerminate()`, call `CoreDataManager.sharedManager.saveContext()`

I'll add a listener to the CoreDataManager so that we autosave on Terminate

**Comment by mdeandreis** [comment]
I need to save the contexto before the user log out. So, I think this is
not the best solution because applicationWillTerminate will not be called

2016-01-11 23:17 GMT-03:00 Zaid Daghestani <notifications@github.com>:

**Comment by zaiddag** [comment]
Just updated with 0.0.5

You can just call `Test.save()`
